/**
 * 🌳 COMPREHENSIVE ROOT MEANINGS DATABASE
 * 
 * Contains meanings for ALL roots in the 500-word database
 * Organized alphabetically by Arabic root
 */

export const rootMeanings = {
  // A - أ
  'أ-ب-د': 'Eternity, perpetuity',
  'أ-ب-ي': 'Refusal, rejection',
  'أ-ت-ي': 'Coming, arriving',
  'أ-ث-ر': 'Trace, effect, tradition',
  'أ-ج-ر': 'Reward, recompense',
  'أ-ح-د': 'Oneness, unity',
  'أ-خ-ذ': 'Taking, seizing',
  'أ-خ-ر': 'Delay, postponement',
  'أ-خ-و': 'Brotherhood, kinship',
  'أ-د-ب': 'Discipline, manners, literature',
  'أ-ذ-ن': 'Permission, ear, hearing',
  'أ-ر-ض': 'Earth, land',
  'أ-ز-ل': 'Eternity without beginning',
  'أ-س-ف': 'Sorrow, regret',
  'أ-س-ل': 'Evening, night time',
  'أ-ك-ل': 'Eating, consuming',
  'أ-ل-ه': 'Divinity, worship',
  'أ-م-ر': 'Command, affair, matter',
  'أ-م-م': 'Nation, community',
  'أ-م-ن': 'Safety, security, belief, trust',
  'أ-ن-س': 'Companionship, humanity',
  'أ-و-ب': 'Returning, repenting',
  'أ-و-ل': 'First, beginning',
  'أ-ي-د': 'Support, strength',
  'أ-ي-ي': 'Sign, verse, miracle',

  // B - ب
  'ب-د-أ': 'Beginning, starting',
  'ب-د-ع': 'Innovation, origination',
  'ب-د-ل': 'Change, substitution',
  'ب-د-ن': 'Body, physical form',
  'ب-ر-أ': 'Creation, innocence',
  'ب-ر-ر': 'Righteousness, goodness, piety',
  'ب-ر-ز': 'Prominence, appearing',
  'ب-ر-ق': 'Lightning, brightness',
  'ب-ر-ك': 'Blessing, kneeling',
  'ب-ر-ه-ن': 'Proof, evidence',
  'ب-س-ط': 'Expansion, spreading',
  'ب-ش-ر': 'Good news, humanity',
  'ب-ص-ر': 'Sight, vision, insight',
  'ب-ط-ل': 'Falsehood, nullity',
  'ب-ط-ن': 'Interior, hidden, belly',
  'ب-ع-ث': 'Sending, resurrection',
  'ب-ع-د': 'Distance, remoteness',
  'ب-غ-ي': 'Transgression, desire',
  'ب-ق-ي': 'Remaining, permanence',
  'ب-ل-غ': 'Reaching, conveying',
  'ب-ل-و': 'Testing, trial',
  'ب-ن-ي': 'Building, structure',
  'ب-ه-ت': 'Confusion, bewilderment',
  'ب-ي-ت': 'House, dwelling',
  'ب-ي-ض': 'Whiteness, brightness',
  'ب-ي-ع': 'Selling, transaction',
  'ب-ي-ن': 'Clarity, explanation',

  // T - ت
  'ت-ب-ب': 'Loss, destruction',
  'ت-ب-ع': 'Following, succession',
  'ت-ر-ب': 'Dust, earth',
  'ت-ل-و': 'Reciting, following',
  'ت-م-م': 'Completion, perfection',
  'ت-و-ب': 'Repentance, returning',

  // TH - ث
  'ث-ب-ت': 'Firmness, stability',
  'ث-ق-ل': 'Heaviness, weight',
  'ث-ل-ث': 'Three, trinity',
  'ث-م-ر': 'Fruit, result',
  'ث-و-ب': 'Garment, reward',

  // J - ج
  'ج-ب-ر': 'Compulsion, restoration',
  'ج-ب-ل': 'Mountain, creation',
  'ج-ث-و': 'Kneeling, sitting',
  'ج-ح-د': 'Denial, rejection',
  'ج-د-د': 'Newness, seriousness',
  'ج-د-ل': 'Argument, debate',
  'ج-ر-ي': 'Running, flowing',
  'ج-ز-ي': 'Recompense, reward',
  'ج-س-د': 'Body, physical form',
  'ج-ع-ل': 'Making, placing, appointing',
  'ج-ل-د': 'Skin, patience',
  'ج-ل-ل': 'Majesty, greatness',
  'ج-م-ع': 'Gathering, collecting',
  'ج-ن-ب': 'Side, avoiding',
  'ج-ن-ح': 'Inclining, wing',
  'ج-ن-ن': 'Concealment, madness, jinn',
  'ج-ه-د': 'Effort, striving',
  'ج-ه-ر': 'Proclamation, loudness',
  'ج-ه-ل': 'Ignorance, foolishness',
  'ج-و-ب': 'Hollow, cavity',
  'ج-و-ر': 'Tyranny, oppression',
  'ج-و-ز': 'Passing, permissibility',
  'ج-و-ع': 'Hunger, starvation',
  'ج-ي-أ': 'Coming, arriving',

  // H - ح
  'ح-ب-ب': 'Love, affection',
  'ح-ب-ر': 'Joy, delight',
  'ح-ب-س': 'Imprisonment, restraint',
  'ح-ب-ط': 'Nullification, failure',
  'ح-ت-م': 'Necessity, obligation',
  'ح-ج-ب': 'Veil, barrier, concealment',
  'ح-ج-ج': 'Argument, pilgrimage',
  'ح-د-ث': 'Happening, occurrence',
  'ح-د-د': 'Limit, boundary',
  'ح-ذ-ر': 'Caution, warning',
  'ح-ر-ث': 'Plowing, cultivation',
  'ح-ر-ج': 'Difficulty, constraint',
  'ح-ر-ر': 'Freedom, liberation',
  'ح-ر-س': 'Guarding, protection',
  'ح-ر-ص': 'Eagerness, greed',
  'ح-ر-ض': 'Incitement, urging',
  'ح-ر-ف': 'Letter, deviation',
  'ح-ر-م': 'Sacred, forbidden',
  'ح-ز-ن': 'Sadness, grief',
  'ح-س-ب': 'Counting, reckoning',
  'ح-س-د': 'Envy, jealousy',
  'ح-س-ن': 'Beauty, goodness, excellence',
  'ح-ش-ر': 'Gathering, assembly',
  'ح-ص-د': 'Harvesting, reaping',
  'ح-ص-ن': 'Fortress, protection',
  'ح-ض-ر': 'Presence, attendance',
  'ح-ف-ظ': 'Protection, preservation, memorization',
  'ح-ق-ق': 'Truth, reality, right',
  'ح-ك-م': 'Wisdom, judgment, ruling',
  'ح-ل-ف': 'Oath, swearing',
  'ح-ل-ل': 'Permissibility, lawfulness',
  'ح-ل-م': 'Forbearance, dream',
  'ح-م-د': 'Praise, gratitude, commendation',
  'ح-م-ل': 'Carrying, bearing, pregnancy',
  'ح-م-ي': 'Protection, heat',
  'ح-ن-ث': 'Breaking oath, sin',
  'ح-و-ر': 'Return, discussion',
  'ح-و-ل': 'Change, transformation',
  'ح-ي-ي': 'Life, living, shyness',

  // KH - خ
  'خ-ب-ر': 'News, information',
  'خ-ب-ث': 'Wickedness, impurity',
  'خ-د-ع': 'Deception, trickery',
  'خ-ذ-ل': 'Abandonment, forsaking',
  'خ-ر-ج': 'Exit, coming out',
  'خ-ز-ي': 'Disgrace, humiliation',
  'خ-س-ر': 'Loss, losing',
  'خ-ش-ع': 'Humility, submission',
  'خ-ش-ي': 'Fear, reverence',
  'خ-ص-م': 'Dispute, argument',
  'خ-ض-ع': 'Submission, yielding',
  'خ-ط-أ': 'Error, mistake',
  'خ-ط-ب': 'Speech, sermon',
  'خ-ف-ف': 'Lightness, easiness',
  'خ-ف-ي': 'Concealment, hiddenness',
  'خ-ل-د': 'Immortality, eternity',
  'خ-ل-ص': 'Sincerity, purity',
  'خ-ل-ط': 'Mixing, confusion',
  'خ-ل-ف': 'Succession, behind',
  'خ-ل-ق': 'Creation, making, character',
  'خ-و-ف': 'Fear, terror',
  'خ-ي-ر': 'Good, goodness, choice',
  'خ-ي-ل': 'Horse, cavalry, imagination',

  // D - د
  'د-ب-ر': 'Back, rear, planning',
  'د-ح-ر': 'Repelling, defeating',
  'د-خ-ل': 'Entering, entry',
  'د-ر-ج': 'Degrees, steps',
  'د-ر-ك': 'Reaching, comprehending',
  'د-ر-ي': 'Knowing, awareness',
  'د-ع-و': 'Calling, inviting, supplication',
  'د-ف-ع': 'Pushing, repelling',
  'د-ل-ل': 'Guidance, indication',
  'د-م-ر': 'Destruction, ruin',
  'د-ن-و': 'Nearness, closeness',
  'د-ه-ر': 'Time, age',
  'د-و-ر': 'Circling, rotating',
  'د-و-م': 'Continuity, permanence',
  'د-ي-ن': 'Religion, judgment, debt',

  // DH - ذ
  'ذ-ب-ح': 'Slaughtering, sacrifice',
  'ذ-ر-أ': 'Creation, offspring',
  'ذ-ك-ر': 'Remembrance, mention, male',
  'ذ-ل-ل': 'Humility, submissiveness',
  'ذ-ه-ب': 'Going, gold',
  'ذ-و-ق': 'Taste, experience',

  // R - ر
  'ر-ب-ب': 'Lord, master, nourisher',
  'ر-ب-ح': 'Profit, gain',
  'ر-ب-ط': 'Binding, connection',
  'ر-ب-و': 'Growth, usury',
  'ر-ت-ب': 'Rank, order',
  'ر-ج-ع': 'Returning, going back',
  'ر-ج-و': 'Hope, expectation',
  'ر-ح-ل': 'Departure, journey',
  'ر-ح-م': 'Mercy, compassion, womb',
  'ر-خ-ص': 'Cheapness, permission',
  'ر-د-د': 'Returning, repelling',
  'ر-س-ل': 'Sending, messengers',
  'ر-ش-د': 'Guidance, maturity',
  'ر-ض-و': 'Satisfaction, approval',
  'ر-ع-د': 'Thunder, fear',
  'ر-ع-ي': 'Pasturing, caring',
  'ر-غ-ب': 'Desire, inclination',
  'ر-ف-ع': 'Raising, elevating',
  'ر-ف-ق': 'Gentleness, kindness',
  'ر-ق-ب': 'Watching, neck',
  'ر-ق-د': 'Sleep, slumber',
  'ر-ك-ب': 'Riding, mounting',
  'ر-ك-ع': 'Bowing, prostrating',
  'ر-م-ي': 'Throwing, shooting',
  'ر-ه-ب': 'Fear, awe',
  'ر-و-ح': 'Spirit, soul, rest',
  'ر-ي-ب': 'Doubt, suspicion',

  // Z - ز
  'ز-ب-ر': 'Strength, scripture',
  'ز-ج-ر': 'Rebuking, restraining',
  'ز-ح-ف': 'Crawling, advancing slowly',
  'ز-خ-ر-ف': 'Adornment, decoration',
  'ز-ر-ع': 'Planting, cultivation',
  'ز-ع-م': 'Claiming, alleging',
  'ز-ك-و': 'Purification, growth, charity',
  'ز-ل-ل': 'Slipping, error',
  'ز-ل-ز-ل': 'Earthquake, shaking',
  'ز-ن-ي': 'Adultery, fornication',
  'ز-و-ج': 'Pair, spouse, type',
  'ز-و-ر': 'Falsehood, visiting',
  'ز-ي-د': 'Increase, addition',
  'ز-ي-ن': 'Adornment, beautification',

  // S - س
  'س-أ-ل': 'Asking, questioning',
  'س-ب-ب': 'Cause, reason, means',
  'س-ب-ح': 'Glorification, swimming',
  'س-ب-ع': 'Seven, sevenfold',
  'س-ب-ق': 'Preceding, racing',
  'س-ت-ر': 'Covering, concealing',
  'س-ج-د': 'Prostration, worship',
  'س-ج-ل': 'Recording, register',
  'س-ح-ر': 'Magic, enchantment',
  'س-ح-ق': 'Crushing, grinding',
  'س-خ-ر': 'Subjugation, mockery',
  'س-ر-ر': 'Secret, joy, bed',
  'س-ر-ع': 'Speed, quickness',
  'س-ر-ف': 'Extravagance, excess',
  'س-ط-ر': 'Line, writing',
  'س-ع-د': 'Happiness, fortune',
  'س-ع-ي': 'Striving, effort',
  'س-ف-ر': 'Travel, journey, book',
  'س-ف-ك': 'Shedding, spilling',
  'س-ف-ه': 'Foolishness, light-mindedness',
  'س-ق-ط': 'Falling, dropping',
  'س-ق-ي': 'Watering, giving drink',
  'س-ك-ت': 'Silence, stillness',
  'س-ك-ن': 'Dwelling, tranquility',
  'س-ل-م': 'Peace, safety, submission, soundness',
  'س-م-ع': 'Hearing, listening',
  'س-م-و': 'Height, sky, naming',
  'س-ن-ن': 'Way, practice, tooth',
  'س-و-أ': 'Evil, badness',
  'س-و-ر': 'Wall, fence',
  'س-و-ق': 'Driving, market',
  'س-و-ي': 'Equality, straightness',
  'س-ي-ر': 'Traveling, walking',

  // SH - ش
  'ش-ر-ب': 'Drinking',
  'ش-ر-ح': 'Explanation, expanding',
  'ش-ر-ر': 'Evil, spark',
  'ش-ر-ط': 'Condition, stipulation',
  'ش-ر-ع': 'Legislation, path',
  'ش-ر-ف': 'Honor, nobility',
  'ش-ر-ق': 'Rising, east',
  'ش-ر-ك': 'Partnership, polytheism',
  'ش-ط-ط': 'Excess, extremism',
  'ش-ع-ر': 'Feeling, poetry, hair',
  'ش-ف-ع': 'Intercession, pairing',
  'ش-ف-ق': 'Fear, compassion',
  'ش-ف-ي': 'Healing, clarity',
  'ش-ق-ق': 'Splitting, difficulty',
  'ش-ك-ر': 'Gratitude, thankfulness',
  'ش-ك-ك': 'Doubt, uncertainty',
  'ش-ه-د': 'Witnessing, testimony',
  'ش-ي-ء': 'Thing, something',

  // S - ص
  'ص-ب-ر': 'Patience, perseverance',
  'ص-ح-ب': 'Companionship, association',
  'ص-د-د': 'Turning away, preventing',
  'ص-د-ر': 'Chest, emanating, beginning',
  'ص-د-ع': 'Splitting, proclaiming',
  'ص-د-ف': 'Turning away, aversion',
  'ص-د-ق': 'Truthfulness, charity',
  'ص-ر-ط': 'Path, way',
  'ص-ر-ف': 'Turning away, change',
  'ص-ع-د': 'Ascending, rising',
  'ص-ع-ق': 'Thunderbolt, shock',
  'ص-غ-ر': 'Smallness, humiliation',
  'ص-ل-ب': 'Hardness, backbone',
  'ص-ل-ح': 'Righteousness, peace, reform',
  'ص-ل-و': 'Prayer, blessing, connection',
  'ص-م-ت': 'Silence, stillness',
  'ص-ن-ع': 'Making, craftsmanship',
  'ص-و-ب': 'Correctness, aiming',
  'ص-و-ر': 'Form, image, picture',
  'ص-و-م': 'Fasting, abstinence',
  'ص-ي-ح': 'Cry, shout',

  // D - ض
  'ض-ر-ب': 'Striking, example',
  'ض-ر-ر': 'Harm, damage',
  'ض-ع-ف': 'Weakness, doubling',
  'ض-ل-ل': 'Straying, error',
  'ض-ي-ع': 'Loss, wasting',
  'ض-ي-ق': 'Narrowness, distress',

  // T - ط
  'ط-ب-ع': 'Sealing, nature',
  'ط-ر-د': 'Expelling, chasing',
  'ط-ر-ف': 'Edge, side, blinking',
  'ط-ر-ق': 'Knocking, path, way',
  'ط-ع-م': 'Food, taste, eating',
  'ط-غ-ي': 'Transgression, tyranny',
  'ط-ل-ب': 'Seeking, requesting',
  'ط-ل-ع': 'Rising, appearing, informing',
  'ط-م-س': 'Effacing, obliterating',
  'ط-و-ر': 'Stage, mountain',
  'ط-و-ع': 'Obedience, willingness',
  'ط-و-ف': 'Circling, surrounding',
  'ط-و-ل': 'Length, prolongation',
  'ط-ه-ر': 'Purification, cleanliness',
  'ط-ي-ب': 'Goodness, pleasantness',
  'ط-ي-ر': 'Flying, birds',

  // DH - ظ
  'ظ-ل-م': 'Injustice, darkness, wrongdoing',
  'ظ-ن-ن': 'Assumption, thinking, suspicion',
  'ظ-ه-ر': 'Appearance, back, manifestation',

  // ' - ع
  'ع-ب-د': 'Worship, servitude, slavery',
  'ع-ت-و': 'Transgression, arrogance',
  'ع-ث-ر': 'Stumbling, discovering',
  'ع-ج-ب': 'Wonder, amazement',
  'ع-ج-ل': 'Haste, calf',
  'ع-د-د': 'Counting, number',
  'ع-د-ل': 'Justice, equity',
  'ع-د-و': 'Enmity, transgression',
  'ع-ذ-ب': 'Punishment, torment',
  'ع-ر-ج': 'Ascending, lameness',
  'ع-ر-ش': 'Throne, dwelling',
  'ع-ر-ض': 'Presenting, width, worldly goods',
  'ع-ر-ف': 'Knowing, custom, goodness',
  'ع-ز-ز': 'Might, honor, strength',
  'ع-ز-ل': 'Isolation, removal',
  'ع-س-ر': 'Difficulty, hardship',
  'ع-ش-ر': 'Ten, association',
  'ع-ص-ي': 'Disobedience, rebelling',
  'ع-ظ-م': 'Greatness, bone',
  'ع-ف-و': 'Pardoning, effacing',
  'ع-ق-ب': 'Consequence, heel, punishment',
  'ع-ق-د': 'Contract, knot, belief',
  'ع-ق-ل': 'Intellect, reason, restraining',
  'ع-ل-م': 'Knowledge, knowing, marking',
  'ع-ل-و': 'Height, elevation, transgression',
  'ع-م-ر': 'Life, prosperity, building',
  'ع-م-ل': 'Work, action, deed',
  'ع-م-ي': 'Blindness, confusion',
  'ع-ن-د': 'Nearness, presence, with',
  'ع-ه-د': 'Covenant, promise, era',
  'ع-و-ذ': 'Seeking refuge, protection',
  'ع-و-د': 'Returning, wood',
  'ع-ي-ش': 'Living, life',
  'ع-ي-ن': 'Eye, spring, essence',

  // GH - غ
  'غ-ب-ن': 'Deception, cheating',
  'غ-د-و': 'Morning, going early',
  'غ-ر-ب': 'West, setting, strangeness',
  'غ-ر-ر': 'Deception, delusion',
  'غ-ز-و': 'Raiding, conquering',
  'غ-س-ق': 'Darkness, intense cold',
  'غ-س-ل': 'Washing, cleansing',
  'غ-ش-و': 'Covering, overwhelming',
  'غ-ض-ب': 'Anger, wrath',
  'غ-ف-ر': 'Forgiveness, covering, protection',
  'غ-ف-ل': 'Heedlessness, neglect',
  'غ-ل-ب': 'Victory, overcoming',
  'غ-ل-ظ': 'Thickness, harshness',
  'غ-ل-ل': 'Chains, treachery',
  'غ-ل-و': 'Excess, extremism',
  'غ-م-م': 'Grief, sorrow, covering',
  'غ-ن-م': 'Spoils, sheep',
  'غ-ن-ي': 'Richness, independence',
  'غ-ي-ب': 'Absence, unseen',
  'غ-ي-ر': 'Other, change',

  // F - ف
  'ف-ت-ح': 'Opening, victory, judgment',
  'ف-ت-ن': 'Trial, temptation, persecution',
  'ف-ج-ر': 'Dawn, wickedness',
  'ف-ح-ش': 'Obscenity, indecency',
  'ف-خ-ر': 'Pride, boasting',
  'ف-د-ي': 'Ransom, redemption',
  'ف-ر-ح': 'Joy, rejoicing',
  'ف-ر-ر': 'Fleeing, escaping',
  'ف-ر-ش': 'Spreading, bed, moth',
  'ف-ر-ض': 'Obligation, appointing',
  'ف-ر-ط': 'Excess, preceding',
  'ف-ر-ع': 'Branch, pharaoh',
  'ف-ر-ق': 'Separation, distinction',
  'ف-ز-ع': 'Fear, terror',
  'ف-س-د': 'Corruption, mischief',
  'ف-س-ق': 'Transgression, disobedience',
  'ف-ش-ل': 'Failure, weakness',
  'ف-ض-ل': 'Favor, bounty, surplus',
  'ف-ط-ر': 'Breaking fast, creation, nature',
  'ف-ع-ل': 'Action, doing, deed',
  'ف-ق-ر': 'Poverty, need',
  'ف-ق-ه': 'Understanding, jurisprudence',
  'ف-ك-ر': 'Thinking, reflection',
  'ف-ل-ح': 'Success, prosperity',
  'ف-ن-ن': 'Art, variety, branch',
  'ف-و-ز': 'Success, salvation',
  'ف-ي-ض': 'Overflow, abundance',

  // Q - ق
  'ق-ب-ض': 'Grasping, withholding',
  'ق-ب-ل': 'Accepting, before, kissing',
  'ق-ت-ر': 'Dust, constriction',
  'ق-ت-ل': 'Killing, fighting',
  'ق-د-ر': 'Power, destiny, measuring',
  'ق-د-س': 'Holiness, purity',
  'ق-د-م': 'Advancement, foot',
  'ق-ر-أ': 'Reading, reciting, gathering',
  'ق-ر-ب': 'Nearness, approaching',
  'ق-ر-ر': 'Stability, decree',
  'ق-ر-ن': 'Pairing, joining, generation',
  'ق-س-ط': 'Justice, equity',
  'ق-س-م': 'Dividing, swearing',
  'ق-ص-د': 'Intention, moderation',
  'ق-ص-ر': 'Shortening, palace',
  'ق-ص-ص': 'Story, narrative',
  'ق-ض-ي': 'Judging, decreeing, finishing',
  'ق-ط-ع': 'Cutting, severing',
  'ق-ع-د': 'Sitting, remaining',
  'ق-ل-ب': 'Heart, turning, transforming',
  'ق-ل-ل': 'Fewness, smallness',
  'ق-م-ر': 'Moon, whiteness',
  'ق-ن-ت': 'Devotion, obedience',
  'ق-ن-ط': 'Despair, hopelessness',
  'ق-و-م': 'Standing, people, straightness',
  'ق-و-ي': 'Strength, power',
  'ق-ي-م': 'Value, standing, management',

  // K - ك
  'ك-ب-ر': 'Greatness, arrogance',
  'ك-ت-ب': 'Writing, recording, book',
  'ك-ت-م': 'Concealing, hiding',
  'ك-ث-ر': 'Abundance, multitude',
  'ك-د-ح': 'Toiling, struggling',
  'ك-ذ-ب': 'Lying, falsehood',
  'ك-ر-م': 'Generosity, nobility, honor',
  'ك-ر-ه': 'Hatred, dislike',
  'ك-س-ب': 'Earning, acquiring',
  'ك-ش-ف': 'Uncovering, revealing',
  'ك-ظ-م': 'Suppressing anger, grief',
  'ك-ف-ر': 'Disbelief, covering, ingratitude',
  'ك-ف-ف': 'Restraining, withholding',
  'ك-ف-ل': 'Guaranteeing, caring for',
  'ك-ل-ف': 'Burden, task',
  'ك-ل-ل': 'Weariness, totality',
  'ك-ل-م': 'Speech, word, wound',
  'ك-م-ل': 'Completion, perfection',
  'ك-ن-ز': 'Treasure, hoarding',
  'ك-و-ن': 'Being, existence, creation',
  'ك-ي-د': 'Plotting, scheming',
  'ك-ي-ل': 'Measuring, weighing',

  // L - ل
  'ل-ب-س': 'Wearing, confusion',
  'ل-ث-و': 'Delaying, tarrying',
  'ل-ح-م': 'Flesh, meat',
  'ل-س-ن': 'Tongue, language',
  'ل-ط-ف': 'Gentleness, kindness, subtlety',
  'ل-ع-ب': 'Playing, sport',
  'ل-ع-ن': 'Cursing, expelling',
  'ل-غ-و': 'Vain talk, nonsense',
  'ل-ف-ت': 'Turning, diverting',
  'ل-ق-ي': 'Meeting, encountering',
  'ل-و-م': 'Blaming, reproach',
  'ل-ي-ل': 'Night, darkness',

  // M - م
  'م-ت-ع': 'Enjoyment, provision',
  'م-ث-ل': 'Likeness, example',
  'م-ج-د': 'Glory, majesty',
  'م-ح-ص': 'Purification, testing',
  'م-ح-ق': 'Destruction, effacing',
  'م-د-د': 'Extension, help, prolongation',
  'م-ر-ج': 'Mixing, confusion',
  'م-ر-ر': 'Passing, bitterness',
  'م-ر-ض': 'Illness, disease',
  'م-س-س': 'Touching, affliction',
  'م-س-ك': 'Holding, grasping',
  'م-ش-ي': 'Walking, going',
  'م-ص-ر': 'City, Egypt',
  'م-ط-ر': 'Rain, pouring',
  'م-ع-ن': 'Facility, aid',
  'م-ك-ث': 'Remaining, staying',
  'م-ك-ر': 'Planning, scheming',
  'م-ك-ن': 'Enabling, empowering',
  'م-ل-أ': 'Filling, assembly, chiefs',
  'م-ل-ك': 'Possession, kingship',
  'م-ن-ع': 'Preventing, withholding',
  'م-ن-ن': 'Favor, obligation',
  'م-و-ت': 'Death, dying',
  'م-ي-ز': 'Distinguishing, separating',
  'م-ي-ل': 'Inclining, leaning',

  // N - ن
  'ن-ب-أ': 'News, prophecy',
  'ن-ب-ت': 'Growing, vegetation',
  'ن-ج-و': 'Salvation, star',
  'ن-ح-ر': 'Slaughtering, chest',
  'ن-د-م': 'Regret, remorse',
  'ن-ذ-ر': 'Warning, vow',
  'ن-ز-ع': 'Pulling out, disputing',
  'ن-ز-غ': 'Inciting, whispering',
  'ن-ز-ل': 'Descending, sending down, alighting',
  'ن-س-خ': 'Abrogating, copying',
  'ن-س-ل': 'Offspring, progeny',
  'ن-س-ي': 'Forgetting, neglecting',
  'ن-ش-ر': 'Spreading, publishing, resurrection',
  'ن-ص-ح': 'Advising, sincerity',
  'ن-ص-ر': 'Help, victory, support',
  'ن-ط-ق': 'Speech, pronunciation',
  'ن-ظ-ر': 'Looking, waiting, considering',
  'ن-ع-م': 'Blessing, favor, comfort',
  'ن-ف-خ': 'Blowing, breathing',
  'ن-ف-ر': 'Fleeing, going forth',
  'ن-ف-س': 'Soul, self, breath',
  'ن-ف-ع': 'Benefit, profit',
  'ن-ف-ق': 'Spending, hypocrisy',
  'ن-ق-ص': 'Deficiency, decreasing',
  'ن-ق-ض': 'Breaking, violating',
  'ن-ك-ر': 'Denying, evil, unknown',
  'ن-م-م': 'Backbiting, slander',
  'ن-ه-ي': 'Forbidding, prohibition',
  'ن-و-ر': 'Light, illumination',
  'ن-و-م': 'Sleep, slumber',

  // H - ه
  'ه-د-ي': 'Guidance, direction, gift',
  'ه-ذ-ب': 'Refining, punishing',
  'ه-ز-ء': 'Mockery, ridicule',
  'ه-ز-ز': 'Shaking, moving',
  'ه-ل-ك': 'Destruction, perishing',
  'ه-م-م': 'Determination, worry',
  'ه-و-ن': 'Ease, humiliation',
  'ه-و-ي': 'Falling, desire, abyss',

  // W - و
  'و-ث-ق': 'Trust, firmness',
  'و-ج-د': 'Finding, existence',
  'و-ج-ل': 'Fear, awe',
  'و-ج-ه': 'Face, direction, aspect',
  'و-ح-د': 'Oneness, unity',
  'و-ح-ي': 'Revelation, inspiration',
  'و-د-د': 'Love, affection',
  'و-ر-ث': 'Inheritance, inheriting',
  'و-ز-ر': 'Burden, sin, minister',
  'و-س-ع': 'Capacity, width',
  'و-س-و-س': 'Whispering, tempting',
  'و-ص-ف': 'Description, attribute',
  'و-ص-ل': 'Connection, joining',
  'و-ص-ي': 'Enjoining, testament',
  'و-ض-ع': 'Placing, putting down',
  'و-ط-ء': 'Treading, sexual intercourse',
  'و-ع-د': 'Promise, appointment',
  'و-ع-ظ': 'Admonition, preaching',
  'و-ف-ي': 'Fulfilling, completion',
  'و-ق-ت': 'Time, appointed time',
  'و-ق-ع': 'Falling, happening, fighting',
  'و-ق-ف': 'Standing, stopping',
  'و-ق-ي': 'Protection, piety',
  'و-ك-ل': 'Trusting, agency',
  'و-ل-د': 'Giving birth, child',
  'و-ل-ي': 'Guardianship, friendship, authority',
  'و-ه-ب': 'Giving, granting',
  'و-ه-ن': 'Weakness, feebleness',

  // Y - ي
  'ي-أ-س': 'Despair, hopelessness',
  'ي-ت-م': 'Orphanhood, uniqueness',
  'ي-د-ي': 'Hand, power, before',
  'ي-س-ر': 'Ease, facilitation, left',
  'ي-ق-ن': 'Certainty, conviction',
  'ي-م-ن': 'Right, oath, blessing',
  'ي-و-م': 'Day, time period',
};

// Helper function to get root meaning with fallback
export function getRootMeaning(root) {
  return rootMeanings[root] || 'Core concept related to this word family';
}

// Function to get all roots
export function getAllRoots() {
  return Object.keys(rootMeanings);
}

// Function to search roots by meaning
export function searchRootsByMeaning(searchTerm) {
  const term = searchTerm.toLowerCase();
  return Object.entries(rootMeanings)
    .filter(([root, meaning]) => meaning.toLowerCase().includes(term))
    .map(([root, meaning]) => ({ root, meaning }));
}